/**
  ******************************************************************************
  * @file    gnss.c
  * @brief   Interrupt-driven NMEA receiver for a UART-attached GNSS module.
  ******************************************************************************
  * @attention
  *
  * This file is application code and is NOT generated by STM32CubeMX.
  * Regenerating the project leaves it untouched.
  *
  ******************************************************************************
  */

#include "gnss.h"

/* Private defines -----------------------------------------------------------*/

/*
 * Receive ring size. Must be a power of two so the index wrap can use a
 * mask instead of a modulo.
 *
 * 512 bytes buffer roughly 44 ms of traffic at 115200 baud -- enough that
 * a slow callback in the main loop does not cost data.
 */
#define GNSS_RX_RING_SIZE 512u
#define GNSS_RX_RING_MASK (GNSS_RX_RING_SIZE - 1u)

/* Private variables ---------------------------------------------------------*/

static UART_HandleTypeDef   *gnss_uart = NULL;
static GNSS_SentenceCallback gnss_callback = NULL;

/*
 * Receive ring. The interrupt advances the head, GNSS_Poll() advances the
 * tail. With exactly one writer and one reader no critical section is
 * needed, as long as both indices are volatile and each is modified by
 * only one side.
 */
static volatile uint8_t  gnss_rx_ring[GNSS_RX_RING_SIZE];
static volatile uint16_t gnss_rx_head = 0;
static volatile uint16_t gnss_rx_tail = 0;

/* Destination byte of the pending HAL_UART_Receive_IT() */
static uint8_t gnss_rx_isr_byte = 0;

/* Sentence assembly, touched only from GNSS_Poll() */
static char     gnss_sentence[GNSS_SENTENCE_MAX];
static uint16_t gnss_sentence_len = 0;
static uint8_t  gnss_in_sentence = 0;

/* Counters. Those written by the interrupt must be volatile. */
static volatile uint32_t gnss_bytes_received = 0;
static volatile uint32_t gnss_uart_errors = 0;
static volatile uint32_t gnss_ring_overflows = 0;
static volatile uint32_t gnss_last_byte_tick = 0;
static volatile uint8_t  gnss_last_byte = 0;

static uint32_t gnss_sentences_received = 0;
static uint32_t gnss_oversized_sentences = 0;
static uint32_t gnss_last_sentence_tick = 0;

/* Private function prototypes -----------------------------------------------*/

static int  GNSS_RingPop(uint8_t *byte);
static void GNSS_ProcessByte(uint8_t byte);

/* Interrupt callbacks -------------------------------------------------------*/

/**
 * @brief Reception callback invoked from HAL_UART_IRQHandler().
 *
 * Runs in interrupt context and therefore does the bare minimum: store the
 * byte and re-arm the next reception. Everything else -- parsing, logging --
 * happens in GNSS_Poll().
 */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart != gnss_uart)
    {
        return;
    }

    uint16_t next = (uint16_t)((gnss_rx_head + 1u) & GNSS_RX_RING_MASK);

    if (next == gnss_rx_tail)
    {
        /*
         * Ring is full: the main loop is not keeping up. Keep the older
         * bytes and drop the new one, so the buffer is not reset wholesale.
         */
        gnss_ring_overflows++;
    }
    else
    {
        gnss_rx_ring[gnss_rx_head] = gnss_rx_isr_byte;
        gnss_rx_head = next;
    }

    gnss_bytes_received++;
    gnss_last_byte = gnss_rx_isr_byte;
    gnss_last_byte_tick = HAL_GetTick();

    HAL_UART_Receive_IT(huart, &gnss_rx_isr_byte, 1);
}

/**
 * @brief Error callback invoked from HAL_UART_IRQHandler().
 *
 * Important: on a blocking error (overrun, receiver timeout) the HAL aborts
 * the pending reception. Without re-arming here, the first such error would
 * silence the receiver permanently.
 *
 * On non-blocking errors (framing, noise, parity) the transfer stays alive
 * and HAL_UART_Receive_IT() simply returns HAL_BUSY, which is harmless.
 */
void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
    if (huart != gnss_uart)
    {
        return;
    }

    gnss_uart_errors++;

    HAL_UART_Receive_IT(huart, &gnss_rx_isr_byte, 1);
}

/* Public functions ----------------------------------------------------------*/

HAL_StatusTypeDef GNSS_Init(UART_HandleTypeDef *huart,
                            GNSS_SentenceCallback on_sentence)
{
    gnss_uart = huart;
    gnss_callback = on_sentence;

    gnss_rx_head = 0;
    gnss_rx_tail = 0;

    gnss_sentence_len = 0;
    gnss_in_sentence = 0;

    gnss_last_byte_tick = HAL_GetTick();
    gnss_last_sentence_tick = HAL_GetTick();

    return HAL_UART_Receive_IT(gnss_uart, &gnss_rx_isr_byte, 1);
}

void GNSS_Poll(void)
{
    uint8_t byte;

    while (GNSS_RingPop(&byte))
    {
        GNSS_ProcessByte(byte);
    }
}

void GNSS_GetStatus(GNSS_Status *out)
{
    if (out == NULL)
    {
        return;
    }

    out->bytes_received      = gnss_bytes_received;
    out->sentences_received  = gnss_sentences_received;
    out->uart_errors         = gnss_uart_errors;
    out->ring_overflows      = gnss_ring_overflows;
    out->oversized_sentences = gnss_oversized_sentences;
    out->last_byte_tick      = gnss_last_byte_tick;
    out->last_sentence_tick  = gnss_last_sentence_tick;
    out->last_byte           = gnss_last_byte;
}

/* Private functions ---------------------------------------------------------*/

/**
 * @brief Takes one byte out of the receive ring.
 *
 * @retval 1 if a byte was returned, 0 if the ring was empty.
 */
static int GNSS_RingPop(uint8_t *byte)
{
    if (gnss_rx_tail == gnss_rx_head)
    {
        return 0;
    }

    *byte = gnss_rx_ring[gnss_rx_tail];
    gnss_rx_tail = (uint16_t)((gnss_rx_tail + 1u) & GNSS_RX_RING_MASK);

    return 1;
}

/**
 * @brief Feeds one received byte into the sentence assembler.
 *
 * Only sentences starting with '$' are collected, so binary traffic from a
 * misconfigured receiver does not end up as one huge line in the log.
 */
static void GNSS_ProcessByte(uint8_t byte)
{
    /* A new NMEA sentence always starts with '$'. */
    if (byte == '$')
    {
        gnss_sentence_len = 0;
        gnss_in_sentence = 1;

        gnss_sentence[gnss_sentence_len++] = '$';

        return;
    }

    /*
     * Before the first '$' the data is ignored for assembly purposes.
     * It is still counted in bytes_received.
     */
    if (!gnss_in_sentence)
    {
        return;
    }

    /* Carriage return is not part of the payload. */
    if (byte == '\r')
    {
        return;
    }

    /* Line feed terminates the sentence. */
    if (byte == '\n')
    {
        if (gnss_sentence_len > 0)
        {
            gnss_sentence[gnss_sentence_len] = '\0';

            gnss_sentences_received++;
            gnss_last_sentence_tick = HAL_GetTick();

            if (gnss_callback != NULL)
            {
                gnss_callback(gnss_sentence);
            }
        }

        gnss_sentence_len = 0;
        gnss_in_sentence = 0;

        return;
    }

    /* Leave room for the terminator. */
    if (gnss_sentence_len < (GNSS_SENTENCE_MAX - 1u))
    {
        gnss_sentence[gnss_sentence_len++] = (char)byte;
    }
    else
    {
        /*
         * No line ending within GNSS_SENTENCE_MAX characters: almost
         * certainly not a valid NMEA sentence. Drop it and resynchronise
         * on the next '$'.
         */
        gnss_sentence_len = 0;
        gnss_in_sentence = 0;
        gnss_oversized_sentences++;
    }
}
