/**
  ******************************************************************************
  * @file    nmea.c
  * @brief   Minimal NMEA 0183 decoder for GGA, GSA, GSV and RMC sentences.
  ******************************************************************************
  * @attention
  *
  * This file is application code and is NOT generated by STM32CubeMX.
  * Regenerating the project leaves it untouched.
  *
  ******************************************************************************
  */

#include "nmea.h"

/* Private defines -----------------------------------------------------------*/

/** Longest field this decoder needs to copy out ("dddmm.mmmm" and friends). */
#define NMEA_FIELD_MAX 16u

/* Private function prototypes -----------------------------------------------*/

static int      NMEA_ChecksumOk(const char *sentence);
static int      NMEA_Field(const char *sentence, uint8_t index,
                           char *buf, uint8_t buflen);
static uint32_t NMEA_Scaled(const char *text, uint8_t decimals);
static int32_t  NMEA_Coordinate(const char *value, char hemisphere);
static void     NMEA_ApplyTime(NMEA_Data *data, const char *text);

/* Public functions ----------------------------------------------------------*/

void NMEA_Reset(NMEA_Data *data)
{
    if (data == NULL)
    {
        return;
    }

    data->data_valid = 0u;
    data->position_valid = 0u;
    data->fix_type = NMEA_FIX_NONE;
    data->fix_quality = 0u;
    data->satellites_used = 0u;
    data->satellites_visible = 0u;
    data->hdop_milli = 0u;
    data->latitude_udeg = 0;
    data->longitude_udeg = 0;
    data->altitude_dm = 0;
    data->utc_hour = 0u;
    data->utc_minute = 0u;
    data->utc_second = 0u;
    data->sentences_parsed = 0u;
    data->checksum_errors = 0u;
    data->sentences_ignored = 0u;
}

int NMEA_Parse(NMEA_Data *data, const char *sentence)
{
    char field[NMEA_FIELD_MAX];
    char hemisphere[NMEA_FIELD_MAX];
    const char *type;

    if ((data == NULL) || (sentence == NULL) || (sentence[0] != '$'))
    {
        return 0;
    }

    /*
     * "$GPGGA" -- two characters of talker id (GP, GN, GA, BD, ...) then
     * three characters of sentence type. Anything shorter cannot be valid.
     */
    for (uint8_t i = 0u; i < 6u; i++)
    {
        if (sentence[i] == '\0')
        {
            return 0;
        }
    }

#ifdef NMEA_VERIFY_CHECKSUM
    if (!NMEA_ChecksumOk(sentence))
    {
        data->checksum_errors++;
        return 0;
    }
#endif

    type = &sentence[3];

    /* ---------------------------------------------------------------- */
    /* GGA -- time, position, fix quality, satellites used, HDOP, alt.   */
    /* ---------------------------------------------------------------- */
    if ((type[0] == 'G') && (type[1] == 'G') && (type[2] == 'A'))
    {
        if (NMEA_Field(sentence, 1u, field, NMEA_FIELD_MAX))
        {
            NMEA_ApplyTime(data, field);
        }

        if (NMEA_Field(sentence, 2u, field, NMEA_FIELD_MAX) &&
            NMEA_Field(sentence, 3u, hemisphere, NMEA_FIELD_MAX))
        {
            data->latitude_udeg = NMEA_Coordinate(field, hemisphere[0]);
            data->position_valid = 1u;
        }

        if (NMEA_Field(sentence, 4u, field, NMEA_FIELD_MAX) &&
            NMEA_Field(sentence, 5u, hemisphere, NMEA_FIELD_MAX))
        {
            data->longitude_udeg = NMEA_Coordinate(field, hemisphere[0]);
        }

        if (NMEA_Field(sentence, 6u, field, NMEA_FIELD_MAX))
        {
            data->fix_quality = (uint8_t)NMEA_Scaled(field, 0u);
        }

        if (NMEA_Field(sentence, 7u, field, NMEA_FIELD_MAX))
        {
            data->satellites_used = (uint8_t)NMEA_Scaled(field, 0u);
        }

        if (NMEA_Field(sentence, 8u, field, NMEA_FIELD_MAX))
        {
            data->hdop_milli = (uint16_t)NMEA_Scaled(field, 3u);
        }

        if (NMEA_Field(sentence, 9u, field, NMEA_FIELD_MAX))
        {
            int32_t altitude = (int32_t)NMEA_Scaled(
                (field[0] == '-') ? &field[1] : field, 1u);

            data->altitude_dm = (field[0] == '-') ? -altitude : altitude;
        }

        data->sentences_parsed++;
        return 1;
    }

    /* ---------------------------------------------------------------- */
    /* GSA -- 2D/3D fix type.                                           */
    /* ---------------------------------------------------------------- */
    if ((type[0] == 'G') && (type[1] == 'S') && (type[2] == 'A'))
    {
        if (NMEA_Field(sentence, 2u, field, NMEA_FIELD_MAX))
        {
            data->fix_type = (uint8_t)NMEA_Scaled(field, 0u);
        }

        data->sentences_parsed++;
        return 1;
    }

    /* ---------------------------------------------------------------- */
    /* GSV -- satellites in view. Field 3 repeats in every GSV of the    */
    /* group, so reading only the first one would be enough; taking it   */
    /* from each is harmless and simpler.                                */
    /* ---------------------------------------------------------------- */
    if ((type[0] == 'G') && (type[1] == 'S') && (type[2] == 'V'))
    {
        if (NMEA_Field(sentence, 3u, field, NMEA_FIELD_MAX))
        {
            data->satellites_visible = (uint8_t)NMEA_Scaled(field, 0u);
        }

        data->sentences_parsed++;
        return 1;
    }

    /* ---------------------------------------------------------------- */
    /* RMC -- navigation validity flag, plus time and position.          */
    /* ---------------------------------------------------------------- */
    if ((type[0] == 'R') && (type[1] == 'M') && (type[2] == 'C'))
    {
        if (NMEA_Field(sentence, 1u, field, NMEA_FIELD_MAX))
        {
            NMEA_ApplyTime(data, field);
        }

        if (NMEA_Field(sentence, 2u, field, NMEA_FIELD_MAX))
        {
            data->data_valid = (field[0] == 'A') ? 1u : 0u;
        }

        if (NMEA_Field(sentence, 3u, field, NMEA_FIELD_MAX) &&
            NMEA_Field(sentence, 4u, hemisphere, NMEA_FIELD_MAX))
        {
            data->latitude_udeg = NMEA_Coordinate(field, hemisphere[0]);
            data->position_valid = 1u;
        }

        if (NMEA_Field(sentence, 5u, field, NMEA_FIELD_MAX) &&
            NMEA_Field(sentence, 6u, hemisphere, NMEA_FIELD_MAX))
        {
            data->longitude_udeg = NMEA_Coordinate(field, hemisphere[0]);
        }

        data->sentences_parsed++;
        return 1;
    }

    data->sentences_ignored++;
    return 0;
}

/* Private functions ---------------------------------------------------------*/

/**
 * @brief Validates the "*hh" checksum at the end of a sentence.
 *
 * The checksum is the XOR of every character between '$' and '*'.
 *
 * @retval 1 if the checksum is present and matches, 0 otherwise.
 */
static int NMEA_ChecksumOk(const char *sentence)
{
    const char *p = &sentence[1];
    uint8_t sum = 0u;
    uint8_t given = 0u;

    while ((*p != '\0') && (*p != '*'))
    {
        sum ^= (uint8_t)(*p);
        p++;
    }

    if (*p != '*')
    {
        /* No checksum in the sentence at all. */
        return 0;
    }

    for (uint8_t i = 1u; i <= 2u; i++)
    {
        char c = p[i];
        uint8_t value;

        if ((c >= '0') && (c <= '9'))
        {
            value = (uint8_t)(c - '0');
        }
        else if ((c >= 'A') && (c <= 'F'))
        {
            value = (uint8_t)(c - 'A' + 10);
        }
        else if ((c >= 'a') && (c <= 'f'))
        {
            value = (uint8_t)(c - 'a' + 10);
        }
        else
        {
            return 0;
        }

        given = (uint8_t)((given << 4) | value);
    }

    return (given == sum) ? 1 : 0;
}

/**
 * @brief Copies comma-separated field @p index into @p buf.
 *
 * Field 0 is the sentence identifier itself. The checksum separator '*'
 * terminates the last field.
 *
 * @retval 1 if the field exists and is non-empty, 0 otherwise.
 */
static int NMEA_Field(const char *sentence, uint8_t index,
                      char *buf, uint8_t buflen)
{
    const char *p = sentence;
    uint8_t field = 0u;
    uint8_t n = 0u;

    while (field < index)
    {
        if ((*p == '\0') || (*p == '*'))
        {
            return 0;
        }

        if (*p == ',')
        {
            field++;
        }

        p++;
    }

    while ((*p != '\0') && (*p != ',') && (*p != '*') && (n < (buflen - 1u)))
    {
        buf[n] = *p;
        n++;
        p++;
    }

    buf[n] = '\0';

    return (n > 0u) ? 1 : 0;
}

/**
 * @brief Parses a decimal number into a fixed-point integer.
 *
 * "545.4" with decimals=1 yields 5454, with decimals=3 yields 545400.
 * Excess fractional digits are truncated, missing ones are padded.
 */
static uint32_t NMEA_Scaled(const char *text, uint8_t decimals)
{
    uint32_t value = 0u;
    uint8_t seen_dot = 0u;
    uint8_t frac = 0u;

    while (*text != '\0')
    {
        if (*text == '.')
        {
            seen_dot = 1u;
            text++;
            continue;
        }

        if ((*text < '0') || (*text > '9'))
        {
            break;
        }

        if (seen_dot != 0u)
        {
            if (frac == decimals)
            {
                break;
            }

            frac++;
        }

        value = (value * 10u) + (uint32_t)(*text - '0');
        text++;
    }

    while (frac < decimals)
    {
        value *= 10u;
        frac++;
    }

    return value;
}

/**
 * @brief Converts "ddmm.mmmm" plus a hemisphere letter to micro-degrees.
 *
 * NMEA reports degrees and decimal minutes packed into one number, so the
 * minute part has to be split off and divided by 60. Working in units of
 * 1e-4 minutes keeps every intermediate result inside 32 bits: the largest
 * value is longitude 18000.0000 -> 180000000.
 */
static int32_t NMEA_Coordinate(const char *value, char hemisphere)
{
    uint32_t scaled = NMEA_Scaled(value, 4u);
    uint32_t degrees = scaled / 1000000u;
    uint32_t minutes_e4 = scaled - (degrees * 1000000u);
    int32_t result;

    result = (int32_t)((degrees * 1000000u) + ((minutes_e4 * 100u) / 60u));

    if ((hemisphere == 'S') || (hemisphere == 'W'))
    {
        result = -result;
    }

    return result;
}

/**
 * @brief Extracts hh, mm and ss from an "hhmmss.sss" field.
 */
static void NMEA_ApplyTime(NMEA_Data *data, const char *text)
{
    for (uint8_t i = 0u; i < 6u; i++)
    {
        if ((text[i] < '0') || (text[i] > '9'))
        {
            return;
        }
    }

    data->utc_hour   = (uint8_t)(((text[0] - '0') * 10) + (text[1] - '0'));
    data->utc_minute = (uint8_t)(((text[2] - '0') * 10) + (text[3] - '0'));
    data->utc_second = (uint8_t)(((text[4] - '0') * 10) + (text[5] - '0'));
}
