/**
  ******************************************************************************
  * @file    nmea.c
  * @brief   Minimal NMEA 0183 decoder for GGA, GSA, GSV and RMC sentences.
  ******************************************************************************
  * @attention
  *
  * This file is application code and is NOT generated by STM32CubeMX.
  * Regenerating the project leaves it untouched.
  *
  ******************************************************************************
  */

#include "nmea.h"

/* Private defines -----------------------------------------------------------*/

/** Longest field this decoder needs to copy out ("dddmm.mmmm" and friends). */
#define NMEA_FIELD_MAX 16u

/* Private function prototypes -----------------------------------------------*/

static int      NMEA_ChecksumOk(const char *sentence);
static int      NMEA_Field(const char *sentence, uint8_t index,
                           char *buf, uint8_t buflen);
static int      NMEA_IsUnsignedDecimal(const char *text);
static uint32_t NMEA_Scaled(const char *text, uint8_t decimals);
static int      NMEA_Coordinate(const char *value, char hemisphere,
                                uint16_t maximum_degrees, int32_t *result);
static int      NMEA_ApplyPosition(NMEA_Data *data, const char *sentence,
                                   uint8_t latitude_field,
                                   uint8_t longitude_field);
static int      NMEA_ApplyTime(NMEA_Data *data, const char *text);
static int      NMEA_ApplyDate(NMEA_Data *data, const char *text);
static NMEA_Constellation NMEA_TalkerConstellation(const char *sentence);
static NMEA_Constellation NMEA_SystemConstellation(uint32_t system_id);
static NMEA_Constellation NMEA_DetectConstellation(uint16_t svid);
static NMEA_Satellite *NMEA_FindOrAddSatellite(
    NMEA_Data *data, NMEA_Constellation constellation, uint16_t svid);
static void     NMEA_ClearVisible(NMEA_Data *data,
                                  NMEA_Constellation constellation);
static void     NMEA_ClearUsed(NMEA_Data *data,
                               NMEA_Constellation constellation);
static void     NMEA_UpdateReportedVisible(
    NMEA_Data *data, NMEA_Constellation constellation, uint8_t total);

/* Public functions ----------------------------------------------------------*/

void NMEA_Reset(NMEA_Data *data)
{
    if (data == NULL)
    {
        return;
    }

    data->data_valid = 0u;
    data->position_valid = 0u;
    data->time_valid = 0u;
    data->date_valid = 0u;
    data->altitude_valid = 0u;
    data->speed_valid = 0u;
    data->course_valid = 0u;
    data->fix_type = NMEA_FIX_NONE;
    data->fix_quality = 0u;
    data->satellites_used = 0u;
    data->satellites_visible = 0u;
    data->satellites_visible_valid = 0u;
    data->hdop_milli = 0u;
    data->latitude_udeg = 0;
    data->longitude_udeg = 0;
    data->altitude_dm = 0;
    data->utc_hour = 0u;
    data->utc_minute = 0u;
    data->utc_second = 0u;
    data->utc_day = 0u;
    data->utc_month = 0u;
    data->utc_year = 0u;
    data->speed_kmh_milli = 0u;
    data->course_mdeg = 0u;
    data->satellite_count = 0u;
    data->sentences_parsed = 0u;
    data->checksum_errors = 0u;
    data->sentences_ignored = 0u;

    for (uint8_t i = 0u; i < 7u; i++)
    {
        data->satellites_visible_by_constellation[i] = 0u;
    }

    for (uint8_t i = 0u; i < NMEA_MAX_SATELLITES; i++)
    {
        data->satellites[i].svid = 0u;
        data->satellites[i].azimuth_deg = 0u;
        data->satellites[i].elevation_deg = 0u;
        data->satellites[i].snr_dbhz = 0u;
        data->satellites[i].constellation = NMEA_CONSTELLATION_UNKNOWN;
        data->satellites[i].elevation_valid = 0u;
        data->satellites[i].azimuth_valid = 0u;
        data->satellites[i].snr_valid = 0u;
        data->satellites[i].visible = 0u;
        data->satellites[i].used = 0u;
    }
}

int NMEA_Parse(NMEA_Data *data, const char *sentence)
{
    char field[NMEA_FIELD_MAX];
    const char *type;

    if ((data == NULL) || (sentence == NULL) || (sentence[0] != '$'))
    {
        return 0;
    }

    /*
     * "$GPGGA" -- two characters of talker id (GP, GN, GA, BD, ...) then
     * three characters of sentence type. Anything shorter cannot be valid.
     */
    for (uint8_t i = 0u; i < 6u; i++)
    {
        if (sentence[i] == '\0')
        {
            return 0;
        }
    }

#ifdef NMEA_VERIFY_CHECKSUM
    if (!NMEA_ChecksumOk(sentence))
    {
        data->checksum_errors++;
        return 0;
    }
#endif

    type = &sentence[3];

    /* ---------------------------------------------------------------- */
    /* GGA -- time, position, fix quality, satellites used, HDOP, alt.   */
    /* ---------------------------------------------------------------- */
    if ((type[0] == 'G') && (type[1] == 'G') && (type[2] == 'A'))
    {
        if (NMEA_Field(sentence, 1u, field, NMEA_FIELD_MAX))
        {
            NMEA_ApplyTime(data, field);
        }

        data->fix_quality = 0u;
        if (NMEA_Field(sentence, 6u, field, NMEA_FIELD_MAX) &&
            NMEA_IsUnsignedDecimal(field))
        {
            data->fix_quality = (uint8_t)NMEA_Scaled(field, 0u);
        }

        data->position_valid =
            ((data->fix_quality != 0u) &&
             NMEA_ApplyPosition(data, sentence, 2u, 4u)) ? 1u : 0u;

        if (NMEA_Field(sentence, 7u, field, NMEA_FIELD_MAX))
        {
            data->satellites_used = (uint8_t)NMEA_Scaled(field, 0u);
        }

        if (NMEA_Field(sentence, 8u, field, NMEA_FIELD_MAX))
        {
            data->hdop_milli = (uint16_t)NMEA_Scaled(field, 3u);
        }

        if (NMEA_Field(sentence, 9u, field, NMEA_FIELD_MAX) &&
            NMEA_IsUnsignedDecimal((field[0] == '-') ? &field[1] : field))
        {
            int32_t altitude = (int32_t)NMEA_Scaled(
                (field[0] == '-') ? &field[1] : field, 1u);

            data->altitude_dm = (field[0] == '-') ? -altitude : altitude;
            data->altitude_valid = 1u;
        }
        else
        {
            data->altitude_valid = 0u;
        }

        data->sentences_parsed++;
        return 1;
    }

    /* ---------------------------------------------------------------- */
    /* GSA -- 2D/3D fix type.                                           */
    /* ---------------------------------------------------------------- */
    if ((type[0] == 'G') && (type[1] == 'S') && (type[2] == 'A'))
    {
        NMEA_Constellation constellation = NMEA_TalkerConstellation(sentence);

        if (NMEA_Field(sentence, 2u, field, NMEA_FIELD_MAX))
        {
            data->fix_type = (uint8_t)NMEA_Scaled(field, 0u);
        }

        /* NMEA 4.x optionally appends a GNSS system ID after VDOP. */
        if (NMEA_Field(sentence, 18u, field, NMEA_FIELD_MAX) &&
            NMEA_IsUnsignedDecimal(field))
        {
            constellation = NMEA_SystemConstellation(NMEA_Scaled(field, 0u));
        }

        NMEA_ClearUsed(data, constellation);

        for (uint8_t index = 3u; index <= 14u; index++)
        {
            NMEA_Constellation satellite_constellation = constellation;
            NMEA_Satellite *satellite;
            uint16_t svid;

            if (!NMEA_Field(sentence, index, field, NMEA_FIELD_MAX) ||
                !NMEA_IsUnsignedDecimal(field))
            {
                continue;
            }

            svid = (uint16_t)NMEA_Scaled(field, 0u);
            if (satellite_constellation == NMEA_CONSTELLATION_UNKNOWN)
            {
                satellite_constellation = NMEA_DetectConstellation(svid);
            }

            satellite = NMEA_FindOrAddSatellite(
                data, satellite_constellation, svid);
            if (satellite != NULL)
            {
                satellite->used = 1u;
            }
        }

        data->sentences_parsed++;
        return 1;
    }

    /* ---------------------------------------------------------------- */
    /* GSV -- visible satellites, four records per sentence.             */
    /* ---------------------------------------------------------------- */
    if ((type[0] == 'G') && (type[1] == 'S') && (type[2] == 'V'))
    {
        NMEA_Constellation constellation = NMEA_TalkerConstellation(sentence);
        uint8_t message_number = 0u;
        uint8_t reported_visible = 0u;

        if (NMEA_Field(sentence, 2u, field, NMEA_FIELD_MAX) &&
            NMEA_IsUnsignedDecimal(field))
        {
            message_number = (uint8_t)NMEA_Scaled(field, 0u);
        }

        if (NMEA_Field(sentence, 3u, field, NMEA_FIELD_MAX) &&
            NMEA_IsUnsignedDecimal(field))
        {
            reported_visible = (uint8_t)NMEA_Scaled(field, 0u);
            NMEA_UpdateReportedVisible(data, constellation, reported_visible);
        }

        /* Message 1 starts a fresh visibility cycle for this system. */
        if (message_number == 1u)
        {
            NMEA_ClearVisible(data, constellation);
        }

        for (uint8_t slot = 0u; slot < 4u; slot++)
        {
            uint8_t base = (uint8_t)(4u + (slot * 4u));
            NMEA_Constellation satellite_constellation = constellation;
            NMEA_Satellite *satellite;
            uint16_t svid;
            uint32_t value;

            if (!NMEA_Field(sentence, base, field, NMEA_FIELD_MAX) ||
                !NMEA_IsUnsignedDecimal(field))
            {
                continue;
            }

            svid = (uint16_t)NMEA_Scaled(field, 0u);
            if (satellite_constellation == NMEA_CONSTELLATION_UNKNOWN)
            {
                satellite_constellation = NMEA_DetectConstellation(svid);
            }

            satellite = NMEA_FindOrAddSatellite(
                data, satellite_constellation, svid);
            if (satellite == NULL)
            {
                continue;
            }

            satellite->visible = 1u;
            satellite->elevation_valid = 0u;
            satellite->azimuth_valid = 0u;
            satellite->snr_valid = 0u;

            if (NMEA_Field(sentence, (uint8_t)(base + 1u),
                           field, NMEA_FIELD_MAX) &&
                NMEA_IsUnsignedDecimal(field))
            {
                value = NMEA_Scaled(field, 0u);
                if (value <= 90u)
                {
                    satellite->elevation_deg = (uint8_t)value;
                    satellite->elevation_valid = 1u;
                }
            }

            if (NMEA_Field(sentence, (uint8_t)(base + 2u),
                           field, NMEA_FIELD_MAX) &&
                NMEA_IsUnsignedDecimal(field))
            {
                value = NMEA_Scaled(field, 0u);
                if (value <= 359u)
                {
                    satellite->azimuth_deg = (uint16_t)value;
                    satellite->azimuth_valid = 1u;
                }
            }

            if (NMEA_Field(sentence, (uint8_t)(base + 3u),
                           field, NMEA_FIELD_MAX) &&
                NMEA_IsUnsignedDecimal(field))
            {
                value = NMEA_Scaled(field, 0u);
                if (value <= 255u)
                {
                    satellite->snr_dbhz = (uint8_t)value;
                    satellite->snr_valid = 1u;
                }
            }
        }

        data->sentences_parsed++;
        return 1;
    }

    /* ---------------------------------------------------------------- */
    /* RMC -- navigation validity flag, plus time and position.          */
    /* ---------------------------------------------------------------- */
    if ((type[0] == 'R') && (type[1] == 'M') && (type[2] == 'C'))
    {
        if (NMEA_Field(sentence, 1u, field, NMEA_FIELD_MAX))
        {
            NMEA_ApplyTime(data, field);
        }

        data->data_valid = 0u;
        if (NMEA_Field(sentence, 2u, field, NMEA_FIELD_MAX))
        {
            data->data_valid = (field[0] == 'A') ? 1u : 0u;
        }

        data->position_valid =
            ((data->data_valid != 0u) &&
             NMEA_ApplyPosition(data, sentence, 3u, 5u)) ? 1u : 0u;

        /* RMC speed is knots. 1 knot is exactly 1.852 km/h. */
        if ((data->data_valid != 0u) &&
            NMEA_Field(sentence, 7u, field, NMEA_FIELD_MAX) &&
            NMEA_IsUnsignedDecimal(field))
        {
            uint32_t knots_milli = NMEA_Scaled(field, 3u);
            data->speed_kmh_milli = (knots_milli * 1852u) / 1000u;
            data->speed_valid = 1u;
        }
        else
        {
            data->speed_valid = 0u;
        }

        if ((data->data_valid != 0u) &&
            NMEA_Field(sentence, 8u, field, NMEA_FIELD_MAX) &&
            NMEA_IsUnsignedDecimal(field))
        {
            data->course_mdeg = NMEA_Scaled(field, 3u);
            data->course_valid = 1u;
        }
        else
        {
            data->course_valid = 0u;
        }

        if (NMEA_Field(sentence, 9u, field, NMEA_FIELD_MAX))
        {
            data->date_valid = NMEA_ApplyDate(data, field) ? 1u : 0u;
        }

        data->sentences_parsed++;
        return 1;
    }

    data->sentences_ignored++;
    return 0;
}

/* Private functions ---------------------------------------------------------*/

/**
 * @brief Validates the "*hh" checksum at the end of a sentence.
 *
 * The checksum is the XOR of every character between '$' and '*'.
 *
 * @retval 1 if the checksum is present and matches, 0 otherwise.
 */
static int NMEA_ChecksumOk(const char *sentence)
{
    const char *p = &sentence[1];
    uint8_t sum = 0u;
    uint8_t given = 0u;

    while ((*p != '\0') && (*p != '*'))
    {
        sum ^= (uint8_t)(*p);
        p++;
    }

    if (*p != '*')
    {
        /* No checksum in the sentence at all. */
        return 0;
    }

    for (uint8_t i = 1u; i <= 2u; i++)
    {
        char c = p[i];
        uint8_t value;

        if ((c >= '0') && (c <= '9'))
        {
            value = (uint8_t)(c - '0');
        }
        else if ((c >= 'A') && (c <= 'F'))
        {
            value = (uint8_t)(c - 'A' + 10);
        }
        else if ((c >= 'a') && (c <= 'f'))
        {
            value = (uint8_t)(c - 'a' + 10);
        }
        else
        {
            return 0;
        }

        given = (uint8_t)((given << 4) | value);
    }

    return (given == sum) ? 1 : 0;
}

/**
 * @brief Copies comma-separated field @p index into @p buf.
 *
 * Field 0 is the sentence identifier itself. The checksum separator '*'
 * terminates the last field.
 *
 * @retval 1 if the field exists and is non-empty, 0 otherwise.
 */
static int NMEA_Field(const char *sentence, uint8_t index,
                      char *buf, uint8_t buflen)
{
    const char *p = sentence;
    uint8_t field = 0u;
    uint8_t n = 0u;

    while (field < index)
    {
        if ((*p == '\0') || (*p == '*'))
        {
            return 0;
        }

        if (*p == ',')
        {
            field++;
        }

        p++;
    }

    while ((*p != '\0') && (*p != ',') && (*p != '*') && (n < (buflen - 1u)))
    {
        buf[n] = *p;
        n++;
        p++;
    }

    buf[n] = '\0';

    return (n > 0u) ? 1 : 0;
}

/**
 * @brief Parses a decimal number into a fixed-point integer.
 *
 * "545.4" with decimals=1 yields 5454, with decimals=3 yields 545400.
 * Excess fractional digits are truncated, missing ones are padded.
 */
static uint32_t NMEA_Scaled(const char *text, uint8_t decimals)
{
    uint32_t value = 0u;
    uint8_t seen_dot = 0u;
    uint8_t frac = 0u;

    while (*text != '\0')
    {
        if (*text == '.')
        {
            seen_dot = 1u;
            text++;
            continue;
        }

        if ((*text < '0') || (*text > '9'))
        {
            break;
        }

        if (seen_dot != 0u)
        {
            if (frac == decimals)
            {
                break;
            }

            frac++;
        }

        value = (value * 10u) + (uint32_t)(*text - '0');
        text++;
    }

    while (frac < decimals)
    {
        value *= 10u;
        frac++;
    }

    return value;
}

static int NMEA_IsUnsignedDecimal(const char *text)
{
    uint8_t digits = 0u;
    uint8_t dots = 0u;

    while (*text != '\0')
    {
        if ((*text >= '0') && (*text <= '9'))
        {
            digits++;
        }
        else if ((*text == '.') && (dots == 0u))
        {
            dots++;
        }
        else
        {
            return 0;
        }

        text++;
    }

    return (digits > 0u) ? 1 : 0;
}

/**
 * @brief Converts "ddmm.mmmm" plus a hemisphere letter to micro-degrees.
 *
 * NMEA reports degrees and decimal minutes packed into one number, so the
 * minute part has to be split off and divided by 60. Working in units of
 * 1e-4 minutes keeps every intermediate result inside 32 bits: the largest
 * value is longitude 18000.0000 -> 180000000.
 */
static int NMEA_Coordinate(const char *value, char hemisphere,
                           uint16_t maximum_degrees, int32_t *result)
{
    uint32_t scaled = NMEA_Scaled(value, 4u);
    uint32_t degrees = scaled / 1000000u;
    uint32_t minutes_e4 = scaled - (degrees * 1000000u);
    int32_t coordinate;

    if (!NMEA_IsUnsignedDecimal(value) || (minutes_e4 >= 600000u) ||
        (degrees > maximum_degrees) ||
        ((degrees == maximum_degrees) && (minutes_e4 != 0u)) ||
        ((hemisphere != 'N') && (hemisphere != 'S') &&
         (hemisphere != 'E') && (hemisphere != 'W')))
    {
        return 0;
    }

    coordinate = (int32_t)((degrees * 1000000u) +
                           ((minutes_e4 * 100u) / 60u));

    if ((hemisphere == 'S') || (hemisphere == 'W'))
    {
        coordinate = -coordinate;
    }

    *result = coordinate;
    return 1;
}

static int NMEA_ApplyPosition(NMEA_Data *data, const char *sentence,
                              uint8_t latitude_field,
                              uint8_t longitude_field)
{
    char latitude[NMEA_FIELD_MAX];
    char latitude_hemisphere[NMEA_FIELD_MAX];
    char longitude[NMEA_FIELD_MAX];
    char longitude_hemisphere[NMEA_FIELD_MAX];
    int32_t latitude_udeg;
    int32_t longitude_udeg;

    if (!NMEA_Field(sentence, latitude_field, latitude, NMEA_FIELD_MAX) ||
        !NMEA_Field(sentence, (uint8_t)(latitude_field + 1u),
                    latitude_hemisphere, NMEA_FIELD_MAX) ||
        !NMEA_Field(sentence, longitude_field, longitude, NMEA_FIELD_MAX) ||
        !NMEA_Field(sentence, (uint8_t)(longitude_field + 1u),
                    longitude_hemisphere, NMEA_FIELD_MAX) ||
        ((latitude_hemisphere[0] != 'N') &&
         (latitude_hemisphere[0] != 'S')) ||
        ((longitude_hemisphere[0] != 'E') &&
         (longitude_hemisphere[0] != 'W')) ||
        !NMEA_Coordinate(latitude, latitude_hemisphere[0], 90u,
                         &latitude_udeg) ||
        !NMEA_Coordinate(longitude, longitude_hemisphere[0], 180u,
                         &longitude_udeg))
    {
        return 0;
    }

    data->latitude_udeg = latitude_udeg;
    data->longitude_udeg = longitude_udeg;
    return 1;
}

/**
 * @brief Extracts hh, mm and ss from an "hhmmss.sss" field.
 */
static int NMEA_ApplyTime(NMEA_Data *data, const char *text)
{
    for (uint8_t i = 0u; i < 6u; i++)
    {
        if ((text[i] < '0') || (text[i] > '9'))
        {
            data->time_valid = 0u;
            return 0;
        }
    }

    if ((text[0] > '2') || ((text[0] == '2') && (text[1] > '3')) ||
        (text[2] > '5') || (text[4] > '5'))
    {
        data->time_valid = 0u;
        return 0;
    }

    data->utc_hour   = (uint8_t)(((text[0] - '0') * 10) + (text[1] - '0'));
    data->utc_minute = (uint8_t)(((text[2] - '0') * 10) + (text[3] - '0'));
    data->utc_second = (uint8_t)(((text[4] - '0') * 10) + (text[5] - '0'));
    data->time_valid = 1u;
    return 1;
}

static int NMEA_ApplyDate(NMEA_Data *data, const char *text)
{
    uint8_t day;
    uint8_t month;
    uint8_t year;

    for (uint8_t i = 0u; i < 6u; i++)
    {
        if ((text[i] < '0') || (text[i] > '9'))
        {
            return 0;
        }
    }

    day = (uint8_t)(((text[0] - '0') * 10) + (text[1] - '0'));
    month = (uint8_t)(((text[2] - '0') * 10) + (text[3] - '0'));
    year = (uint8_t)(((text[4] - '0') * 10) + (text[5] - '0'));

    if ((day == 0u) || (day > 31u) || (month == 0u) || (month > 12u))
    {
        return 0;
    }

    data->utc_day = day;
    data->utc_month = month;
    data->utc_year = (uint16_t)(((year >= 80u) ? 1900u : 2000u) + year);
    return 1;
}

static NMEA_Constellation NMEA_TalkerConstellation(const char *sentence)
{
    if ((sentence[1] == 'G') && (sentence[2] == 'P'))
    {
        return NMEA_CONSTELLATION_GPS;
    }
    if ((sentence[1] == 'G') && (sentence[2] == 'L'))
    {
        return NMEA_CONSTELLATION_GLONASS;
    }
    if ((sentence[1] == 'G') && (sentence[2] == 'A'))
    {
        return NMEA_CONSTELLATION_GALILEO;
    }
    if (((sentence[1] == 'G') && (sentence[2] == 'B')) ||
        ((sentence[1] == 'B') && (sentence[2] == 'D')))
    {
        return NMEA_CONSTELLATION_BEIDOU;
    }
    if ((sentence[1] == 'G') && (sentence[2] == 'Q'))
    {
        return NMEA_CONSTELLATION_QZSS;
    }
    if ((sentence[1] == 'G') && (sentence[2] == 'I'))
    {
        return NMEA_CONSTELLATION_NAVIC;
    }

    /* GN is a combined talker; the individual SVID must identify it. */
    return NMEA_CONSTELLATION_UNKNOWN;
}

static NMEA_Constellation NMEA_SystemConstellation(uint32_t system_id)
{
    switch (system_id)
    {
        case 1u: return NMEA_CONSTELLATION_GPS;
        case 2u: return NMEA_CONSTELLATION_GLONASS;
        case 3u: return NMEA_CONSTELLATION_GALILEO;
        case 4u: return NMEA_CONSTELLATION_BEIDOU;
        case 5u: return NMEA_CONSTELLATION_QZSS;
        case 6u: return NMEA_CONSTELLATION_NAVIC;
        default: return NMEA_CONSTELLATION_UNKNOWN;
    }
}

static NMEA_Constellation NMEA_DetectConstellation(uint16_t svid)
{
    if ((svid >= 1u) && (svid <= 32u))
    {
        return NMEA_CONSTELLATION_GPS;
    }
    if ((svid >= 65u) && (svid <= 96u))
    {
        return NMEA_CONSTELLATION_GLONASS;
    }
    if ((svid >= 193u) && (svid <= 200u))
    {
        return NMEA_CONSTELLATION_QZSS;
    }
    if ((svid >= 201u) && (svid <= 237u))
    {
        return NMEA_CONSTELLATION_BEIDOU;
    }
    if ((svid >= 301u) && (svid <= 336u))
    {
        return NMEA_CONSTELLATION_GALILEO;
    }
    if ((svid >= 401u) && (svid <= 414u))
    {
        return NMEA_CONSTELLATION_NAVIC;
    }

    return NMEA_CONSTELLATION_UNKNOWN;
}

static NMEA_Satellite *NMEA_FindOrAddSatellite(
    NMEA_Data *data, NMEA_Constellation constellation, uint16_t svid)
{
    for (uint8_t i = 0u; i < data->satellite_count; i++)
    {
        NMEA_Satellite *satellite = &data->satellites[i];

        if ((satellite->constellation == constellation) &&
            (satellite->svid == svid))
        {
            return satellite;
        }
    }

    if (data->satellite_count >= NMEA_MAX_SATELLITES)
    {
        return NULL;
    }

    NMEA_Satellite *satellite = &data->satellites[data->satellite_count++];
    satellite->svid = svid;
    satellite->azimuth_deg = 0u;
    satellite->elevation_deg = 0u;
    satellite->snr_dbhz = 0u;
    satellite->constellation = constellation;
    satellite->elevation_valid = 0u;
    satellite->azimuth_valid = 0u;
    satellite->snr_valid = 0u;
    satellite->visible = 0u;
    satellite->used = 0u;
    return satellite;
}

static void NMEA_ClearVisible(NMEA_Data *data,
                              NMEA_Constellation constellation)
{
    for (uint8_t i = 0u; i < data->satellite_count; i++)
    {
        if ((constellation == NMEA_CONSTELLATION_UNKNOWN) ||
            (data->satellites[i].constellation == constellation))
        {
            data->satellites[i].visible = 0u;
        }
    }
}

static void NMEA_ClearUsed(NMEA_Data *data,
                           NMEA_Constellation constellation)
{
    for (uint8_t i = 0u; i < data->satellite_count; i++)
    {
        if ((constellation == NMEA_CONSTELLATION_UNKNOWN) ||
            (data->satellites[i].constellation == constellation))
        {
            data->satellites[i].used = 0u;
        }
    }
}

static void NMEA_UpdateReportedVisible(
    NMEA_Data *data, NMEA_Constellation constellation, uint8_t total)
{
    if (constellation == NMEA_CONSTELLATION_UNKNOWN)
    {
        data->satellites_visible_by_constellation[0] = total;
        data->satellites_visible = total;
        data->satellites_visible_valid = 1u;
        return;
    }

    data->satellites_visible_by_constellation[(uint8_t)constellation] = total;

    uint16_t sum = 0u;
    for (uint8_t i = 1u; i < 7u; i++)
    {
        sum += data->satellites_visible_by_constellation[i];
    }

    data->satellites_visible = (sum > 255u) ? 255u : (uint8_t)sum;
    data->satellites_visible_valid = 1u;
}
