/**
  ******************************************************************************
  * @file    gnss.h
  * @brief   Interrupt-driven NMEA receiver for a UART-attached GNSS module.
  ******************************************************************************
  * @attention
  *
  * This file is application code and is NOT generated by STM32CubeMX.
  * Regenerating the project leaves it untouched.
  *
  ******************************************************************************
  */

#ifndef GNSS_H
#define GNSS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32h7xx_hal.h"

/**
 * @brief Maximum length of a single NMEA sentence, including the
 *        terminating '\0'.
 *
 * The NMEA 0183 standard caps a sentence at 82 characters. The extra
 * headroom keeps unusual or proprietary sentences intact.
 */
#define GNSS_SENTENCE_MAX 256u

/**
 * @brief Called from GNSS_Poll() once a complete sentence is available.
 *
 * The string is '\0'-terminated, starts with '$' and carries no trailing
 * CR/LF. It points into an internal buffer that is reused as soon as the
 * callback returns -- copy it if you need to keep it.
 *
 * Runs in the context of whoever calls GNSS_Poll(), never in an interrupt,
 * so the callback may take its time (logging, parsing, ...).
 */
typedef void (*GNSS_SentenceCallback)(const char *sentence);

/**
 * @brief Snapshot of the receiver's counters, for diagnostics.
 */
typedef struct
{
    /** Bytes accepted by the UART interrupt, including non-NMEA traffic. */
    uint32_t bytes_received;

    /** Complete sentences handed to the callback. */
    uint32_t sentences_received;

    /** UART-level faults (overrun, framing, noise, parity). */
    uint32_t uart_errors;

    /** Bytes dropped because GNSS_Poll() was not called often enough. */
    uint32_t ring_overflows;

    /** Sentences discarded for exceeding GNSS_SENTENCE_MAX. */
    uint32_t oversized_sentences;

    /** HAL tick at which the last byte arrived. */
    uint32_t last_byte_tick;

    /** HAL tick at which the last complete sentence was decoded. */
    uint32_t last_sentence_tick;

    /** Most recent raw byte -- useful when data arrives but never parses. */
    uint8_t last_byte;
} GNSS_Status;

/**
 * @brief Binds the receiver to a UART and starts interrupt reception.
 *
 * The UART must already be initialised (MX_USARTx_UART_Init) and its
 * global interrupt enabled in the NVIC, otherwise no data will arrive.
 *
 * @param huart     UART the GNSS module is connected to.
 * @param on_sentence Callback for decoded sentences, or NULL to only count.
 * @retval HAL status of arming the first reception.
 */
HAL_StatusTypeDef GNSS_Init(UART_HandleTypeDef *huart,
                            GNSS_SentenceCallback on_sentence);

/**
 * @brief Drains the receive buffer and invokes the callback per sentence.
 *
 * Call this regularly from the main loop. It never blocks; reception
 * continues in the background regardless of how long the caller takes.
 */
void GNSS_Poll(void);

/**
 * @brief Copies the current counters into @p out.
 *
 * The individual fields are read atomically, but not as a consistent set
 * -- an interrupt may land mid-copy. That is fine for diagnostics.
 */
void GNSS_GetStatus(GNSS_Status *out);

#ifdef __cplusplus
}
#endif

#endif /* GNSS_H */
