/**
  ******************************************************************************
  * @file    nmea.h
  * @brief   Minimal NMEA 0183 decoder for GGA, GSA, GSV and RMC sentences.
  ******************************************************************************
  * @attention
  *
  * This file is application code and is NOT generated by STM32CubeMX.
  * Regenerating the project leaves it untouched.
  *
  * All values are stored as scaled integers, never as float. SEGGER's
  * RTT printf supports only c/d/u/x/X/s/p -- there is no %f -- and the
  * fixed scaling keeps the output exact and cheap to format.
  *
  ******************************************************************************
  */

#ifndef NMEA_H
#define NMEA_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

/*
 * Comment this out to accept sentences without validating the trailing
 * "*hh" checksum. Keeping it on costs a few microseconds per sentence and
 * prevents garbled input from being decoded into plausible-looking values.
 */
#define NMEA_VERIFY_CHECKSUM

/** Fix type as reported by GSA field 2. */
#define NMEA_FIX_NONE 1u
#define NMEA_FIX_2D   2u
#define NMEA_FIX_3D   3u

/** Maximum number of satellite records retained at once. */
#define NMEA_MAX_SATELLITES 64u

typedef enum
{
    NMEA_CONSTELLATION_UNKNOWN = 0,
    NMEA_CONSTELLATION_GPS,
    NMEA_CONSTELLATION_GLONASS,
    NMEA_CONSTELLATION_GALILEO,
    NMEA_CONSTELLATION_BEIDOU,
    NMEA_CONSTELLATION_QZSS,
    NMEA_CONSTELLATION_NAVIC
} NMEA_Constellation;

typedef struct
{
    /** Satellite vehicle identifier/PRN as transmitted by the receiver. */
    uint16_t svid;

    /** Azimuth clockwise from true north, 0..359 degrees. */
    uint16_t azimuth_deg;

    /** Elevation above the horizon, 0..90 degrees. */
    uint8_t elevation_deg;

    /** Carrier-to-noise ratio in dB-Hz, if snr_valid is set. */
    uint8_t snr_dbhz;

    NMEA_Constellation constellation;

    /** Measurement and state validity flags. */
    uint8_t elevation_valid;
    uint8_t azimuth_valid;
    uint8_t snr_valid;
    uint8_t visible;
    uint8_t used;
} NMEA_Satellite;

/**
 * @brief Decoded navigation state, accumulated across sentences.
 *
 * A single GNSS output cycle spreads its information over several
 * sentences, so the fields are updated independently as they arrive.
 */
typedef struct
{
    /** 1 once RMC has reported status 'A' (valid navigation data). */
    uint8_t data_valid;

    /** 1 if the latest GGA/RMC reports a complete, currently valid position. */
    uint8_t position_valid;

    /** 1 once a syntactically valid UTC time has been decoded. */
    uint8_t time_valid;

    /** 1 once RMC has supplied a syntactically valid date. */
    uint8_t date_valid;

    /** Validity flags for optional measurements. */
    uint8_t altitude_valid;
    uint8_t speed_valid;
    uint8_t course_valid;

    /** NMEA_FIX_NONE / NMEA_FIX_2D / NMEA_FIX_3D, from GSA. */
    uint8_t fix_type;

    /** GGA field 6: 0 invalid, 1 GPS, 2 DGPS, 4 RTK fixed, 5 RTK float. */
    uint8_t fix_quality;

    /** Satellites used in the solution, from GGA. */
    uint8_t satellites_used;

    /** Total satellites in view as reported directly by GSV. */
    uint8_t satellites_visible;

    /** 1 after at least one valid GSV total has been received. */
    uint8_t satellites_visible_valid;

    /** Per-constellation GSV totals; index uses NMEA_Constellation. */
    uint8_t satellites_visible_by_constellation[7];

    /** Horizontal dilution of precision, x1000 (1234 == 1.234). */
    uint16_t hdop_milli;

    /** Latitude in micro-degrees, negative for south. */
    int32_t latitude_udeg;

    /** Longitude in micro-degrees, negative for west. */
    int32_t longitude_udeg;

    /** Altitude above mean sea level in decimetres (5454 == 545.4 m). */
    int32_t altitude_dm;

    /** UTC time of the last fix. */
    uint8_t utc_hour;
    uint8_t utc_minute;
    uint8_t utc_second;

    /** UTC date from RMC. Years 80..99 map to 1980..1999, others to 2000+. */
    uint8_t utc_day;
    uint8_t utc_month;
    uint16_t utc_year;

    /** Speed over ground in km/h x1000 (12345 == 12.345 km/h). */
    uint32_t speed_kmh_milli;

    /** Course over ground in degrees x1000 (271250 == 271.250 degrees). */
    uint32_t course_mdeg;

    /** Satellite records accumulated from GSV and usage flags from GSA. */
    NMEA_Satellite satellites[NMEA_MAX_SATELLITES];
    uint8_t satellite_count;

    /** Sentences successfully decoded. */
    uint32_t sentences_parsed;

    /** Sentences rejected because the checksum did not match. */
    uint32_t checksum_errors;

    /** Sentences of a type this decoder does not handle. */
    uint32_t sentences_ignored;
} NMEA_Data;

/**
 * @brief Clears all decoded state.
 */
void NMEA_Reset(NMEA_Data *data);

/**
 * @brief Decodes one sentence into @p data.
 *
 * @param data     Accumulated state to update.
 * @param sentence '\0'-terminated sentence starting with '$', without CR/LF.
 * @retval 1 if the sentence was understood and applied, 0 otherwise.
 */
int NMEA_Parse(NMEA_Data *data, const char *sentence);

#ifdef __cplusplus
}
#endif

#endif /* NMEA_H */
